// Generated by scripts/benchmarks/generate-mobile-pdf-fixtures.mjs. Do not edit.
declare const require: (path: string) => number;

export const mobileFixtureRegistry = {
  "small": require("./assets/fixtures/small.pdf"),
  "large-100": require("./assets/fixtures/large-100.pdf"),
  "large-1000": require("./assets/fixtures/large-1000.pdf"),
  "varied-sizes": require("./assets/fixtures/varied-sizes.pdf"),
} as const;
